<?php

/**
 * PluginClearCacheTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginClearCacheTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginClearCacheTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginClearCacheTask');
    }
}