<?php

/**
 * PluginServerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginServerTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object PluginServerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginServer');
    }

    public static function getOrCreateOneByName($name, $ip = null)
    {
        if (!$server = self::getInstance()->getOneByName($name))
        {
            $server = new Server();
            $server->setName($name);
            $server->setIp($ip);
            $server->save();
        }

        return $server;
    }

}