<?php

/**
 * PluginServerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginServerTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object PluginServerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginServer');
    }

    public static function getOrCreateOneByName($name)
    {
        $server = self::getInstance()->findOneBy('name', $name);
        if (!$server)
        {
            // create new server
            $server = new Server();
            $server->setName($name);
            $server->save();
        }

        return $server;
    }

}