<?php

/**
 * PluginClearCacheTaskServerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginClearCacheTaskServerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginClearCacheTaskServerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginClearCacheTaskServer');
    }
}